name: "Generates relnotes"
description: "Generates release notes based on commits"
author: "Louis-Guillaume MORAND, ZHENG Robert"
branding:
  icon: "award"
  color: "orange"
inputs:
  githubToken:
    description: "Token to access GitHub"
    required: true
  newTag:
    description: "New tag"
    required: true
  generateArtifact:
    description: "Generates a changelog.txt"
    required: true
    default: "true"
outputs:
  relnotes:
    description: The generated release notes
runs:
  using: "node20"
  main: "js/index.js"
