name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test the action
        id: relnotes
        uses: ./
        
      - name: Test the generated release notes
        run: echo ${{ steps.relnotes.outputs.relnotes }}
