name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Test the action
        id: relnotes
        uses: ./
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          newTag: v2.0.0
          generateArtifact: true
        
      - name: Test the generated release notes
        run: echo "${{ steps.relnotes.outputs.relnotes }}"
        
      - uses: actions/upload-artifact@v2
        with:
          name: changelog
          path: changelog.txt
