name: CI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to create"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Generate release + changelog
        id: relnotes
        uses: ./
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          newTag: ${{ github.event.inputs.tag }}
          generateArtifact: true

      - name: Test the generated release notes
        run: echo "${{ steps.relnotes.outputs.relnotes }}"

      - uses: actions/upload-artifact@v3
        with:
          name: changelog
          path: changelog.txt
